# Stage 1: Build Application
FROM gradle:9.2.1-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
# build the distribution
RUN gradle installDist --no-daemon

# Stage 2: Create the Runtime Image
FROM amazoncorretto:21-alpine AS runtime
EXPOSE 8080

RUN mkdir /app
# Copy the installed distribution from the build stage
COPY --from=build /home/gradle/src/build/install/kotlin-backend-project /app/

# Set the working directory to the app folder
WORKDIR /app

# Run the startup script generated by the application plugin
ENTRYPOINT ["bin/kotlin-backend-project"]